/**
 * Write `src/version.ts` from `package.json`.
 *
 * `--version` was a typed constant and reported 0.1.2 through four releases, so
 * the one command a user runs to find out whether their install updated was the
 * one thing that never changed. Reading package.json at runtime fixes the npm
 * install and not the compiled standalone binary, which has no package.json to
 * read; baking the string in at build time fixes both.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const body = `// Generated by scripts/gen-version.mjs from package.json. Do not edit.
export const VERSION = '${pkg.version}'
`
const target = new URL('../src/version.ts', import.meta.url)
let current = ''
try {
  current = readFileSync(target, 'utf8')
} catch {
  // first run
}
if (current !== body) writeFileSync(target, body)
